const profileData = {
    "login": "NaomiReeves",
    "id": 10870770,
    "node_id": "MDQ6VXNlcjEwODcwNzcw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/10870770?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NaomiReeves",
    "html_url": "https://github.com/NaomiReeves",
    "followers_url": "https://api.github.com/users/NaomiReeves/followers",
    "following_url": "https://api.github.com/users/NaomiReeves/following{/other_user}",
    "gists_url": "https://api.github.com/users/NaomiReeves/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NaomiReeves/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NaomiReeves/subscriptions",
    "organizations_url": "https://api.github.com/users/NaomiReeves/orgs",
    "repos_url": "https://api.github.com/users/NaomiReeves/repos",
    "events_url": "https://api.github.com/users/NaomiReeves/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NaomiReeves/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Naomi Reeves",
    "company": null,
    "blog": "",
    "location": "San Francisco, CA",
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 15,
    "public_gists": 0,
    "followers": 73,
    "following": 4,
    "created_at": "2015-02-05T19:02:44Z",
    "updated_at": "2020-06-20T00:13:57Z"
}

export default profileData